name: hargapangan

on:
  schedule:
    - cron: '*/30 * * * *'  # setiap 6 jam sekali
  workflow_dispatch:


jobs:
  covid-scrape:
    runs-on: macos-latest
    env:
      ATLAS_URL: ${{ secrets.ATLAS_URL }}
      ATLAS_COLLECTION: ${{ secrets.ATLAS_COLLECTION }}
      ATLAS_DB: ${{ secrets.ATLAS_DB }}
    steps:
      - name: Start time
        run: echo "$(date) ** $(TZ=Asia/Jakarta date)"
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
      - name: Install mongolite package
        run:  'install.packages("mongolite", dependencies = TRUE)'
      - name: Install rvest package
        run: 'install.packages("rvest", dependencies = TRUE)' 
      - name: Install mongolite package
        run:  'install.packages("tidyverse", dependencies = TRUE)'
      - name: Install rvest package
        run: 'install.packages("jsonlite", dependencies = TRUE)' 
      - name: Scrape data hargapangan
        run: Rscript scrape_hargapangan.R
